pub const DOTFILE_FOLDER: &str = ".grayman";
pub const CONFIG_FILE: &str = "grayman.toml";
pub const CACHE_FILE: &str = "cache";
pub const GITIGNORE_CONTENT: &str = r#"# Auto-generated by Grayman
.grayman/
grayman.local.toml
"#;

// pub const LOGS_FOLDER: &str = "logs"; // Inside the DOTFILE_FOLDER
// pub const LOCAL_CONFIG_FILE: &str = "grayman.local.toml";
