pub const DOTFILE_FOLDER: &str = ".grayman";
pub const CONFIG_FILE: &str = "config.toml";
pub const LAST_TASK_FILE: &str = ".last_task";
pub const GITIGNORE_FILE: &str = ".gitignore";
pub const GITIGNORE_CONTENT: &str = r#"# Auto-generated by grayman

# Ignore everything in this folder...
*

# ...except
!.gitignore
!config.toml
"#;
